// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: message.sql

package repo

import (
	"context"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (user1_id, user2_id, match_score, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user1_id, user2_id, match_score, status, created_at
`

type CreateMatchParams struct {
	User1ID    *string `json:"user1_id"`
	User2ID    *string `json:"user2_id"`
	MatchScore *int32  `json:"match_score"`
	Status     *string `json:"status"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.User1ID,
		arg.User2ID,
		arg.MatchScore,
		arg.Status,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.User1ID,
		&i.User2ID,
		&i.MatchScore,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (fname,lname,phoneno,email,password,bio,preferences,profile_picture)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, fname, lname, phoneno, email, password, bio, preferences, profile_picture, created_at
`


  
type CreateUserParams struct {
	Fname          string  `json:"fname"`
	Lname          string  `json:"lname"`
	Phoneno        string  `json:"phoneno"`
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	Bio            string  `json:"bio"`
	Preferences    PrefJson`json:"preferences"`
	ProfilePicture *string `json:"profile_picture"`
}

type PrefJson  struct {
	Pet string `json:"pet"`
	Job string `json:"job"`
}  


func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Fname,
		arg.Lname,
		arg.Phoneno,
		arg.Email,
		arg.Password,
		arg.Bio,
		arg.Preferences,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fname,
		&i.Lname,
		&i.Phoneno,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.Preferences,
		&i.ProfilePicture,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :many
SELECT id, fname, lname, phoneno, email, password, bio, preferences, profile_picture, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Fname,
			&i.Lname,
			&i.Phoneno,
			&i.Email,
			&i.Password,
			&i.Bio,
			&i.Preferences,
			&i.ProfilePicture,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
