// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Match struct {
	ID         string           `json:"id"`
	User1ID    *string          `json:"user1_id"`
	User2ID    *string          `json:"user2_id"`
	MatchScore *int32           `json:"match_score"`
	Status     *string          `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	ID          string           `json:"id"`
	SenderID    *string          `json:"sender_id"`
	ReceiverID  *string          `json:"receiver_id"`
	MessageText string           `json:"message_text"`
	Timestamp   pgtype.Timestamp `json:"timestamp"`
}

type Room struct {
	ID                 string           `json:"id"`
	UserID             *string          `json:"user_id"`
	Location           string           `json:"location"`
	RentPrice          pgtype.Numeric   `json:"rent_price"`
	RoomDetails        []byte           `json:"room_details"`
	AvailabilityStatus *bool            `json:"availability_status"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID             string           `json:"id"`
	Fname          string           `json:"fname"`
	Lname          string           `json:"lname"`
	Phoneno        string           `json:"phoneno"`
	Email          string           `json:"email"`
	Password       string           `json:"password"`
	Bio            string           `json:"bio"`
	Preferences    PrefJson           `json:"preferences"`
	ProfilePicture *string          `json:"profile_picture"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
